### ISSUE TITLE
Unable to remove source cache - when building a new child image

### ISSUE THREAD

**Issue by vanomashey** [fluent/fluentd-docker-image#100]
Hi guys,

I am trying to build a new custom docker image following the example in the documenation. All examples from documentation are failing on gem source -c command with the error:
Unable to remove source cache

I am not a ruby guru, so help would appreciated. Cannot find in google why this would happen. I guess more users might experience this as long as it is in documentation examples. 

Thank you in advance.

Regards,
Ivan

**Comment by robeatoz** [comment]
I had the same problem and the solution was to use the overlay2 driver rather than the overlay driver, see 
https://docs.docker.com/storage/storagedriver/overlayfs-driver/
