### ISSUE TITLE
 Error installing fluent-plugin-elasticsearch 

### ISSUE THREAD

**Issue by dytmh** [fluent/fluentd-docker-image#105]
Step 5/7 : RUN gem install fluent-plugin-elasticsearch
 ---> Running in ecb9eb354f79
Successfully installed serverengine-2.0.5
Building native extensions.  This could take a while...
ERROR:  Error installing fluent-plugin-elasticsearch:
        ERROR: Failed to build gem native extension.

    current directory: /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9/ext/strptime
/usr/bin/ruby -r ./siteconf20171212-5-1s8xgi2.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /usr/lib/ruby/gems/2.3.0/gems/strptime-0.1.9 for inspection.
Results logged to /usr/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/strptime-0.1.9/gem_make.out
The command '/bin/sh -c gem install fluent-plugin-elasticsearch' returned a non-zero code: 1

**Comment by repeatedly** [comment]
See: https://github.com/fluent/fluentd-docker-image#note

**Comment by cosmo0920** [comment]
Already resolved in https://github.com/uken/fluent-plugin-elasticsearch/issues/509#issuecomment-443677926.
