### ISSUE TITLE
Why expose 24224 5140?

### ISSUE THREAD

**Issue by wjzhangcsu** [fluent/fluentd-docker-image#107]
I am using fluentd-docker-image  0.14.25 alpine .     why do I need to expose 24224 5140?  I use lsof -i and netstat -tunlp| grep 5140 && 24224 .However ,I get nothing about these ports.

**Comment by repeatedly** [comment]
These are default port of `in_forward` and `in_syslog`.
These plugins are widely used in many environment so opened by default.

**Comment by wjzhangcsu** [comment]
OK,I am a beginner about fluentd. When I use 
<source>
  @type tail
  ...
</source> 
<match>
  @type elasticsearch
  ...
</match>
,do I need to expose these ports?

**Comment by repeatedly** [comment]
No because these plugins don't listen a port.

**Comment by wjzhangcsu** [comment]
OK,I am a beginner about fluentd. When I use
'''
<source>
    @type tail 
    ... 
</source>
<match>
    @type elasticsearch 
    ... 
<match>
'''
do I need to expose these ports?

**Comment by wjzhangcsu** [comment]
@repeatedly   Thanks you very much.

**Comment by wjzhangcsu** [comment]
"@type tail" and "@type elasticsearch" don't listen a port.
