### ISSUE TITLE
All scanned images have critical vulnerabilities

### ISSUE THREAD

**Issue by aiueogawa** [fluent/fluentd-docker-image#108]
In DockerHub, all scanned images seem to have two vulnerabilities.
One is critical one ruby 2.3.6-r0 causes and the other is major one ncurses 6.0_p20170701-r0 causes.

Please get rid of these vulnerabilities.

**Comment by repeatedly** [comment]
How to fix this?
alpine and debian images don't have fixed packages?

**Comment by bodsch** [comment]
Alpine 3.5 was released on 2016-12-22 and is outdated.
Please, use 3.7!
