### ISSUE TITLE
stable/latest tags are not updated

### ISSUE THREAD

**Issue by aiueogawa** [fluent/fluentd-docker-image#109]
@repeatedly 
Documentation says

>We will change stable/latest to use v1.0 instead of v0.12 at Jan 1, 2018.

, but this has not been done yet.

Please update `latest` and `stable` tags.

**Comment by repeatedly** [comment]
Fixed by https://github.com/fluent/fluentd-docker-image/commit/ea1b107bc25edc92162d539cab46d0de7b7d336d
