### ISSUE TITLE
Openshift will allow only non-root user. This container fails

### ISSUE THREAD

**Issue by meduri99** [fluent/fluentd-docker-image#114]
I am trying to use this image on my OpenShift Instance. But since there is a restriction to run the containers on pods as non-root user, this image is failing to run.

Is there an alternative?

**Comment by repeatedly** [comment]
Hmm... maybe, asking it on OpenShift community is better.

**Comment by rmacian** [comment]
I am on the same boat, the problem lays here:

https://github.com/fluent/fluentd-docker-image/blob/master/v0.14/alpine/entrypoint.sh

I think this tries to keep the UID to avoid permissions problems but Openshift has guides to allow this

See "Support Arbitrary User IDs" in
https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-origin-specific-guidelines

**Comment by repeatedly** [comment]
Fluetnd has FLUENTD_UID env to specify uid at runtime.
Openshift can't use this mechanizm to adjust uid?
