### ISSUE TITLE
Adding support for power(ppc64le) for travis builds

### ISSUE THREAD

**Issue by ghatwala** [fluent/fluentd-docker-image#120]
Hi All,

I have added support for power ( ppc64le ) arch on travis-ci builds via my forked repository - https://github.com/ghatwala/fluentd-docker-image

The travis-ci job url - https://travis-ci.org/ghatwala/fluentd-docker-image/builds/389559309 . As can be seen in this job, the versions which failed on power are failing on Intel as well.

For example gpg keys errors seen.
For v1.1/debian -
Intel - https://travis-ci.org/ghatwala/fluentd-docker-image/jobs/389559316#L975
Power -  https://travis-ci.org/ghatwala/fluentd-docker-image/jobs/389559330#L1001

To add support for power for travis build, had to make the following changes.
1. travis.yml - Ensuring that builds are routed to travis-power along with travis-intel 
```
os:
  - linux
  - linux-ppc64le
```
And to make the dockerfile build for power  ....
1. Dockerfile ( for debian based only ) - Dumb-Init version has been updated from  1.2.0 --> 1.2.1 as power binaries are now available for this release - https://github.com/Yelp/dumb-init/releases/tag/v1.2.1.

```
ENV DUMB_INIT_VERSION=1.2.1
```

let me know if your views/suggestions/comments if any , so that i can raise a PR to get this going ?

Regards,
Amit

**Comment by ghatwala** [comment]
@repeatedly - any comments on the above ?

**Comment by repeatedly** [comment]
gpg error is key server side issue so it seems no problem for me.

**Comment by ghatwala** [comment]
thanks @repeatedly  for your review comments , will raise a PR shortly on this.

**Comment by seelam** [comment]
are the power images now getting pushed into docker hub?

**Comment by repeatedly** [comment]
We have already sent the PR for docker repository.
We are waiting the merge.

https://github.com/docker-library/official-images/pull/5303

**Comment by ghatwala** [comment]
hey @seelam - Fluentd docker image has been made officially multi-arch now 
Official docker image CI link - https://doi-janky.infosiftr.net/job/multiarch/job/ppc64le/job/fluentd/ and 
dockerhub link - https://hub.docker.com/_/fluentd/
