### ISSUE TITLE
health check

### ISSUE THREAD

**Issue by lukasa1993** [fluent/fluentd-docker-image#129]
what is best way to health check this container ?

**Comment by JiHyunSong** [comment]
👍 

+ Is there any good way to tracking child process (fluentd worker sometimes dead by OOM) dead?

In k8s, provision though daemon-set, can not catch dead of worker process.

**Comment by aibou** [comment]
This URL seems to have been broken because of newest commits.

This may be valid URL:
https://github.com/helm/charts/blob/d0b9568/stable/fluentd-elasticsearch/templates/daemonset.yaml#L106-L139

**Comment by kenhys** [comment]
It might be straight forward to use fluentd daemonset images.
or enable monitor REST interface and so on.

**Comment by kenhys** [comment]
I'll close stale issue.

**Comment by christiansipola** [comment]
My case was in docker compose and not kubenetes and I used `netstat` in the container to find the name of the host and port and then `test: [ "CMD", "wget --spider exanple:27017" ]`
