### ISSUE TITLE
Allow for absolute conf path in FLUENTD_CONF

### ISSUE THREAD

**Issue by profhase** [fluent/fluentd-docker-image#143]
As of now the variable `FLUENTD_CONF` only allows relative paths, assuming `/fluentd/etc` as base path (implicitly).
It would be nice to be able to keep the config both on the host system and inside the container aligned. Therefore the `FLUENTD_CONF` variable should accept absolute paths.

**Comment by repeatedly** [comment]
Could you suggest good way for it?

**Comment by kenhys** [comment]
I'll close stall issue. Thank you for feedback.
