### ISSUE TITLE
windows images haven't been pushed to Docker Hub

### ISSUE THREAD

**Issue by Place1** [fluent/fluentd-docker-image#148]
I can see in this repo there is a dockerfile for a windows container version of fluentd but on DockerHub there is no tag associated with it.

**Comment by repeatedly** [comment]
Automated build limitation by docker hub: https://docs.docker.com/docker-hub/builds/#limitations

**Comment by Place1** [comment]
@repeatedly ahh. I was unaware of the limitation. Is there any chance a maintainer can publish the images?

**Comment by repeatedly** [comment]
I don't have windows dev environment for now.
So there are 2 approaches:

- Someone becomes windows image maintainer of fluentd-docker-image
- Someone build image and I push it

Former is better for community.

**Comment by cosmo0920** [comment]
Windows images are already pushed:
https://hub.docker.com/r/fluent/fluentd/tags?page=1&name=windows
