### ISSUE TITLE
Docker fluentid not PID 1 - container needs SIGKILL to exit.

### ISSUE THREAD

**Issue by ivandotv** [fluent/fluentd-docker-image#15]
Can't cleanly stop the container, docker sends SIGKILL after 10 seconds timeout.
It appears that the fluentd is not PID 1. 
It is started via ruby wrapper script.

**Comment by repeatedly** [comment]
Ah, this change seems to be removed unexpectedly after moved to alpine linux > https://github.com/fluent/fluentd-docker-image/pull/5
Could you test latest Dockerfile with above change?
