### ISSUE TITLE
the image in docker hub is broken

### ISSUE THREAD

**Issue by jeremywu0127** [fluent/fluentd-docker-image#17]
it seems the official image in docker hub is broken !
```[root@cloud /data 11:23:08]# docker images```
```REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE```
```fluent/fluentd      latest              6179c3420517        8 days ago          35.94 MB```

**Comment by repeatedly** [comment]
What does 'broken' mean?

**Comment by repeatedly** [comment]
Please write `broken` detail here.
- fluentd doesn't work?
- can't invoke docker image?
- etc

**Comment by jeremywu0127** [comment]
as I mentioned above ,you can see the total size of the fluentd image is ```35.94MB```, that's what the 'broken' mean

**Comment by repeatedly** [comment]
So you didn't try image, right?

> the total size of the fluentd image

See this: https://github.com/fluent/fluentd-docker-image/pull/9

**Comment by jeremywu0127** [comment]
@repeatedly thx for notification , I did't notice the announce
