### ISSUE TITLE
README on Docker Hub broken

### ISSUE THREAD

**Issue by boldt** [fluent/fluentd-docker-image#171]
The *Customization* paragraph on [Docker Hub](https://hub.docker.com/r/fluent/fluentd/) contains the following line for the Apline version:

```
FROM fluent/fluentd:v1.3-onbuild
....
COPY fluent.conf /fluentd/etc/
COPY entrypoint.sh /bin/
```

Where do I find the entrypoint.sh? I assume, it's [this one](https://github.com/fluent/fluentd-docker-image/blob/master/v1.3/alpine/entrypoint.sh)?

Additionally the, the Debian version does not contain these two lines.

I guess, it is more important to show the `ENTRYFILE` and `CMD` from the original Dockerfiles.

**Comment by boldt** [comment]
More issued with the README:

I just treid the provided `Dockerfile`, The following MWE fails:

```
FROM fluent/fluentd:v1.3-onbuild
```
Building it returns the following error:

```
$ docker build -t boldt/fluentd .
Sending build context to Docker daemon    129kB
Step 1/1 : FROM fluent/fluentd:v1.3-onbuild
# Executing 2 build triggers
COPY failed: stat /var/lib/docker/tmp/docker-builder327670021/fluent.conf: no such file or directory
```

Where is the `COPY` coming from?

**Comment by repeatedly** [comment]
> The Customization paragraph on Docker Hub contains the following line for the Apline version:

`COPY`  is not needed here because base images have it. Just removed from example. Thanks!

**Comment by boldt** [comment]
I'll reopen the issue:

The README now shows `&amp;&amp;` instead of `&&` in the section [Customize Dockerfile to install plugins (optional)](https://hub.docker.com/r/fluent/fluentd/#3-customize-dockerfile-to-install-plugins-optional):

![bildschirmfoto vom 2019-01-24 18 44 59](https://user-images.githubusercontent.com/750793/51697506-41f65280-2008-11e9-836f-180a0d99bbc2.png)

**Comment by repeatedly** [comment]
Hmm... it seems new docker hub rendering issue.

https://github.com/fluent/fluentd-docker-image#alpine-version

If I remember correctly, old docker hub reanders README correctly.
Maybe, new docker hub fails to interpret github's markdown.

**Comment by kenhys** [comment]
This issue was solved.

![image](https://user-images.githubusercontent.com/225841/125028881-b8e21180-e0c3-11eb-8f98-679bef77c42a.png)
