### ISSUE TITLE
Owner of /fluentd

### ISSUE THREAD

**Issue by dontub** [fluent/fluentd-docker-image#172]
The owner and group of `/fluentd` is changed to fluent recursively. (The `fluent.conf` is copied thereafter, so it's owned by root.) Does the user fluent need to write into any directory apart from `/fluentd/log`? If not, it would be enough to change the ownership of `/fluentd/log` only.

**Comment by kenhys** [comment]
Thank you for feedback.

It seems that there is historical reason but not sure...

If it causes the actual problem, let's discuss it then. (I'll close it)
