### ISSUE TITLE
Is FLUENTD_CONF variable deprecated ? 

### ISSUE THREAD

**Issue by alexandersm** [fluent/fluentd-docker-image#174]
Can you please clarify whether FLUENTD_CONF is deprecated now ? 
We have a docket image with several config files inside and used that variable to specify required configuration

**Comment by repeatedly** [comment]
Recent changes follow standard docker way: https://github.com/fluent/fluentd-docker-image#providing-your-own-configuration-file-and-additional-options
But re-add FLUENTD_CONF is not problem for the environment which can't specifiy the filename via command options.

**Comment by repeatedly** [comment]
v1.4 images re-support FLUENTD_CONF environment variable.
