### ISSUE TITLE
Is it possible to add a plugin w/o modifying Dockerfile

### ISSUE THREAD

**Issue by dmgcodevil** [fluent/fluentd-docker-image#176]
I'd like to add a fluent plugin b/c I need to use it in my fluent.conf , for instance: kafka-plugin. I don't see any to add plugin but modifying Dockerfile. Is it possible to specify what plugins I need as an argument for  `docker run `?

**Comment by rivetmichael** [comment]
I am looking for exactly the same question 😄 It seems that it is possible via some options in the `entrypoint.sh` file.
@dmgcodevil did you find a way ?

**Comment by dmgcodevil** [comment]
@rivetmichael nope

**Comment by aymenwerg** [comment]
Did you find a way to resolve this issue because i have the same problem now !!

**Comment by repeatedly** [comment]
If Docker supports executing/getting external resources in `docker run`, we can support this feature.

Basically, create your image is docker/container way.

**Comment by kenhys** [comment]
As repeatedly says, it is straightforward way to create your custom image.

It may works putting plugins under /fluentd/plugins as an alternative, but it is very limited situation to meet your needs.

It seems that situation was not changed since 2021, so I'll close this stalled issue.
