### ISSUE TITLE
Confused as to versioning

### ISSUE THREAD

**Issue by chiefy** [fluent/fluentd-docker-image#18]
If I pull the latest tag, and I pull v0.12.19 they are two different images. One is ubuntu based and one is alpine based (yay!). I like to use discrete versions in my `Dockerfiles` so there are no surprises when I build.

**Comment by repeatedly** [comment]
Next fluentd v0.12.20 will be based on Alpine.
We don't have a plan to re-build older versions.

**Comment by chiefy** [comment]
@repeatedly right, but "latest" has been published to docker hub, and uses 0.12.19 correct?

**Comment by repeatedly** [comment]
> "latest" has been published to docker hub

Yes. Docker Hub automatically generates this tag.

> uses 0.12.19 correct?

Correct.

**Comment by chiefy** [comment]
ok, just to be clear for anyone searching:

fluent/fluentd:latest = alpine linux w/ 0.12.19
fluent/fluentd:v0.12.19 = ubuntu w/ 0.12.19
