### ISSUE TITLE
Running fluentd and fluentd-ui on different containers

### ISSUE THREAD

**Issue by rogervila** [fluent/fluentd-docker-image#185]
Hello,

I wonder if running fluentd-ui on the same container as fluentd is a good idea, since its a good practice to keep only one process per docker container.

is there any example running fluentd and fluentd-ui running separately?

Thank you.

**Comment by kenhys** [comment]
fluentd-ui may be useful as simple log viewer, but fluentd-ui is not maintained actively anymore and it is stale for a long time.
I think that It is not good approach use with it because it is not container friendly, so I'll close this issue.
