### ISSUE TITLE
Cannot install plugins in container building process

### ISSUE THREAD

**Issue by tom932** [fluent/fluentd-docker-image#186]
I have the following issue:

I have a `Dockerfile` where I install some plugins. This worked fine until base-version `v1.3.1`

Now, I want to update the base-version to `v1.4.2-2.0`, I also tried `v1.4`, and some 1.5 version. This doesn't work anymore, I get the following error message:

```
Step 2/5 : RUN gem install fluent-plugin-rewrite-tag-filter -v 2.2.0
 ERROR:  While executing gem ... (Gem::FilePermissionError)
     You don't have write permissions for the /usr/lib/ruby/gems/2.5.0 directory.
```

It seems to be the same problem as https://github.com/fluent/fluentd-docker-image/issues/10 but that issue states to be fixed in 2016, therefore, I am not sure if it is the same issue and opened a new one.

Here is my simplified (I removed some plugins to make it shorter) `Dockerfile`
```
FROM fluent/fluentd:v1.4.2-2.0

RUN gem install fluent-plugin-rewrite-tag-filter -v 2.2.0

ENV FLUENTD_OPT=""
ENV FLUENTD_CONF="fluent.conf"

CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

What can I do to upgrade my fluentd-version?

**Comment by repeatedly** [comment]
See https://github.com/fluent/fluentd-docker-image#alpine-version

**Comment by tom932** [comment]
Thanks for the fast response, worked perfectly :)
