### ISSUE TITLE
Is v1.3 really still the latest "stable" version?

### ISSUE THREAD

**Issue by chewi** [fluent/fluentd-docker-image#194]
I just want to confirm that you still consider the stable tags to be relevant. The [fluentd download page](https://www.fluentd.org/download) says **v1.0, current stable** but then has the v1.7 gem listed below. There was also a v1.3.3 release but the stable tags were never moved beyond v1.3.2. I can't see any other official mention of a stable release.

If the tags are still relevant then please could you give some idea of what version they will be bumped to next? In the meantime, it would be great if you could refresh v1.3 with the Debian + Ruby 2.6 image because Ruby 2.3 leaks memory really badly to the point of being unusable. I tried this myself and didn't face any complications.

**Comment by chewi** [comment]
I wouldn't normally ping an issue like this but we need to make a decision around this very soon and there is literally no one else we can ask. Please clarify the situation.

**Comment by repeatedly** [comment]
> I can't see any other official mention of a stable release.

If this `stable` means `stable` tag, README mentions it. See following section:

> https://github.com/fluent/fluentd-docker-image#for-older-images
> These images/tags are kept for backward compatibility. No update anymore. Use "current images" instead.

**Comment by chewi** [comment]
Many thanks for this and apologies for not spotting that paragraph. I must have skipped ahead to the **stable** heading. :confounded:
