### ISSUE TITLE
Upgrade debian's base image to buster

### ISSUE THREAD

**Issue by repeatedly** [fluent/fluentd-docker-image#199]
https://hub.docker.com/_/ruby repository now has buster images, so we can switch to buster.

**Comment by fgreinacher** [comment]
Are you working on this @repeatedly? If not, I’d give it a shot.

**Comment by repeatedly** [comment]
@fgreinacher I have very small patch to test default config:

```
diff --git a/Dockerfile.template.erb b/Dockerfile.template.erb
index bf19f49..4ab1594 100644
--- a/Dockerfile.template.erb
+++ b/Dockerfile.template.erb
@@ -20,7 +20,7 @@ FROM alpine:3.9
 <% if is_armhf %>
 FROM arm32v7/ruby:2.6-stretch
 <% else %>
-FROM ruby:2.6-slim-stretch
+FROM ruby:2.6-slim-buster
 <% end %>
 <% end %>
 <% end %>
```

if you test buster image and no problem with your config, this is great. Of course, patches are welcome ;)
