### ISSUE TITLE
Docker build stucks Windows Image

### ISSUE THREAD

**Issue by leandroandrade-hotmart** [fluent/fluentd-docker-image#208]
Hi everyone!
I'm trying build a windows image docker based on `mcr.microsoft.com/windows/servercore:ltsc2019`
for that, i just change the FROM of v1.9/windows/Dockerfile and after that i  triyed run `docker build -t fluentd-windows .` and the process stucks with the last log:
```
19 gems installed
Successfully installed win32-service-1.0.1
1 gem installed
Successfully installed win32-ipc-0.7.0
1 gem installed
Successfully installed win32-event-0.6.3
1 gem installed
Successfully installed windows-pr-1.2.6
1 gem installed
*** Removed specs cache ***
```
Anyone knows how to solve this?
Thanks

**Comment by cosmo0920** [comment]
Hi, I'm building Windows images.

First, Docker for Windows is slow to creating layers.



> I'm trying build a windows image docker based on `mcr.microsoft.com/windows/servercore:ltsc2019`
> for that, i just change the FROM of v1.9/windows/Dockerfile and after that i triyed run `docker build -t fluentd-windows .` and the process stucks with the last log:

Hmm, I got stuck this line in from 5 to 10 minutes, but after from 5 to 10 minutes building process is resuming and working as expected.

I recommend to split [this step](https://github.com/fluent/fluentd-docker-image/blob/master/v1.9/windows/Dockerfile#L15) into a few steps like:

```dockerfile
RUN refreshenv \
&& ridk install 2 3 # ridk install is very slow due to many file upgrading and installing
RUN echo gem: --no-document >> C:\ProgramData\gemrc \
&& gem install cool.io -v 1.5.4 --platform ruby \
&& gem install oj -v 3.3.10 \
&& gem install json -v 2.2.0 \
&& gem install fluentd -v 1.9.1 \
&& gem install win32-service -v 1.0.1 \
&& gem install win32-ipc -v 0.7.0 \
&& gem install win32-event -v 0.6.3 \
&& gem install windows-pr -v 1.2.6
RUN gem sources --clear-all # This line can be removed because just for reducing image size
```

**Comment by artisticcheese** [comment]
This is wrong approach since it inflates image size and shall not have any effect on total build times. 
Deleting files in subsequent image layers DOES NOT REDUCE total image size. In fact it increases it. See here https://artisticcheese.wordpress.com/2018/12/02/docker-image-layers-lessons-learned/

**Comment by pragadeeshraju** [comment]
+1,
same issue, just got stuck after    (tried removing the cache clear lines)
```
Successfully installed windows-pr-1.2.6
1 gem installed
```

**Comment by mr-smithers-excellent** [comment]
This seems to be working now if you use the [v1.10 Dockerfile](https://github.com/fluent/fluentd-docker-image/blob/master/v1.10/windows/Dockerfile). I was able to build using `mcr.microsoft.com/windows/servercore:ltsc2019` as the base then successfully deploy to a Windows EKS node in a daemon set.

That being said, it would be great if there was a tag available on the official repository for `ltsc2019`

**Comment by cosmo0920** [comment]
We'll provide Windows Server Core ltsc2019 image.
I'm closing this issue.
