### ISSUE TITLE
Unable to install package 

### ISSUE THREAD

**Issue by dgarros** [fluent/fluentd-docker-image#21]
Hi 

I'm trying to build my own container on top of this one but I'm not able to install a  package with apk
Is it expected ? Am I missing something ? 

I'm getting this error
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

I'm sorry if this is a simple mistake, this is my first container based on Alpine, I'm not familiar with it yet
Thanks
Damien

Here is my Dockerfile
```
FROM fluent/fluentd:v0.12.21
MAINTAINER Damien Garros <dgarros@gmail.com>

RUN apk --update add grep ruby-dev
```

And log
```
Sending build context to Docker daemon   108 kB
Step 1 : FROM fluent/fluentd:v0.12.21
# Executing 2 build triggers...
Step 1 : COPY fluent.conf /fluentd/etc/
 ---> Using cache
Step 1 : COPY plugins /fluentd/plugins/
 ---> Using cache
 ---> 2174b2d46cca
Step 2 : MAINTAINER Damien Garros <dgarros@gmail.com>
 ---> Using cache
 ---> 4c67b3818839
Step 3 : RUN apk --update add grep ruby-dev
 ---> Running in 993a8205131d
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```

**Comment by tagomoris** [comment]
Is USER == 'fluent' in that line?
`USER root` looks required before `RUN apk`.

**Comment by dgarros** [comment]
As simple as that :)
Thanks for your help

**Comment by rajiff** [comment]
Can we add this information to Docker Hub page, please

**Comment by repeatedly** [comment]
Docker Hub page, not README?

**Comment by kochsoft** [comment]
Ran into the same, although the example Dockerfile included "USER root". I removed that line, because I deemed it to be unnecessary, believing the default user is root anyway. Reintroduced it now, adding a comment to that Dockerfile to prevent a repetition of that mistake at a later time.
