### ISSUE TITLE
Adding plugins with docker-compse, Dockefile and GEM

### ISSUE THREAD

**Issue by mattroell** [fluent/fluentd-docker-image#212]
**I'm using a docker-compose file:**
```yaml
fluentd:
    hostname: fluentd
    container_name: fluentd
    image: fluentd/fluentd:edge-debian
    networks:
      - internal
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    command:
      - '--config=/fluentd/etc/fluent.conf'  
    volumes:
      - /var/lib/docker-data/fluentd:/fluentd/log
      - /var/lib/docker-data/fluentd/etc:/fluentd/etc
    build: ./fluentd
```
**The Dockerfile:**
```dockerfile
FROM fluent/fluentd:edge-debian

USER root
RUN ["gem", "install", "fluent-plugin-elasticsearch"]
RUN ["gem", "install", "fluent-plugin-fortigate-syslog-parser"]
USER fluent
```
**I run this command:** 
```console
 docker-compose up -d fluentd
```
**There are no issues when it runs/builds (output below):**
```log
Building fluentd
Step 1/5 : FROM fluent/fluentd:edge-debian
 ---> f3ca49de8f29
Step 2/5 : USER root
 ---> Running in 1d12ac5adf48
Removing intermediate container 1d12ac5adf48
 ---> e95ea84763bb
Step 3/5 : RUN ["gem", "install", "fluent-plugin-elasticsearch"]
 ---> Running in c4e0ef027b33
Successfully installed excon-0.73.0
Successfully installed multi_json-1.14.1
Successfully installed multipart-post-2.1.1
Successfully installed faraday-0.17.3
Successfully installed elasticsearch-transport-7.5.0
Successfully installed elasticsearch-api-7.5.0
Successfully installed elasticsearch-7.5.0
Successfully installed fluent-plugin-elasticsearch-4.0.7
8 gems installed
Removing intermediate container c4e0ef027b33
 ---> 81c3fb2ca543
Step 4/5 : RUN ["gem", "install", "fluent-plugin-fortigate-syslog-parser"]
 ---> Running in 574da0367fff
Successfully installed fluent-plugin-fortigate-syslog-parser-0.1.1
1 gem installed
Removing intermediate container 574da0367fff
 ---> 557c6256ca30
Step 5/5 : USER fluent
 ---> Running in db2b0fbfe1e2
Removing intermediate container db2b0fbfe1e2
 ---> 9af50ac54aba
Successfully built 9af50ac54aba
Successfully tagged fluentd/fluentd:edge-debian
WARNING: Image for service fluentd was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating fluentd ...
Creating fluentd ... done
```
**Here is my very basic fluent.conf:**
```aconf
<source>
  @type forward
  port 24224
</source>

<source>
 @type udp
  port 9910
  bind 0.0.0.0
  <parse>
    @type FortigateSyslogParser
  </parse>
  tag parsed.fortigate
 </source>
```
It fails to run with the second source ( @type FortigateSyslogParser), here is the error log:

```
2020-04-01 17:27:43 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-04-01 17:27:43 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.0.7'
2020-04-01 17:27:43 +0000 [info]: gem 'fluent-plugin-fortigate-syslog-parser' version '0.1.1'
2020-04-01 17:27:43 +0000 [info]: gem 'fluentd' version '1.10.0'
2020-04-01 17:27:43 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown parser plugin 'FortigateSyslogParser'. Run 'gem search -rd fluent-plugin' to find plugins"
```

For some reason the plugins are not found, when I run this command, fluent-gem list The plugins are listed:
fluent-plugin-elasticsearch (4.0.7)
fluent-plugin-fortigate-syslog-parser (0.1.1)

So I'm not sure what's going on, beside that fact that the plugin's are not found.

**Comment by cosmo0920** [comment]
>  ```
> <source>
>   @type udp
>   port 9910
>   bind 0.0.0.0
>   <parse>
>     @type FortigateSyslogParser
>   </parse>
>   tag parsed.fortigate
>  </source>

`@type FortigateSyslogParser` should be `@type fortigate_log_parser`. `@type` should work with registered plugin name not plugin class name.

**Comment by apacoco9861** [comment]
so sad, still not work, any idea? many thanks,

root@sys:/efk# docker-compose up fluentd
efk_elasticsearch_1 is up-to-date
Recreating efk_fluentd_1 ... done
Attaching to efk_fluentd_1
fluentd_1        | 2020-10-08 03:53:47 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1        | 2020-10-08 03:53:47 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.2.0'
fluentd_1        | 2020-10-08 03:53:47 +0000 [info]: gem 'fluent-plugin-fortigate-log-parser' version '0.2.1'
fluentd_1        | 2020-10-08 03:53:47 +0000 [info]: gem 'fluent-plugin-fortigate-syslog-parser' version '0.1.1'
fluentd_1        | 2020-10-08 03:53:47 +0000 [info]: gem 'fluentd' version '1.11.3'
fluentd_1        | 2020-10-08 03:53:48 +0000 [info]: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
fluentd_1        | 2020-10-08 03:53:48 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown parser plugin 'FortigateSyslogParser'. Run 'gem search -rd fluent-plugin' to find plugins"
efk_fluentd_1 exited with code 1
root@sys:/efk# vi fluentd/conf/fluent.conf
root@sys:/efk# docker-compose up fluentd
efk_elasticsearch_1 is up-to-date
Starting efk_fluentd_1 ... done
Attaching to efk_fluentd_1
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.2.0'
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: gem 'fluent-plugin-fortigate-log-parser' version '0.2.1'
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: gem 'fluent-plugin-fortigate-syslog-parser' version '0.1.1'
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: gem 'fluentd' version '1.11.3'
fluentd_1        | 2020-10-08 03:54:02 +0000 [info]: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
fluentd_1        | 2020-10-08 03:54:02 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown parser plugin 'fortigate_log_parser'. Run 'gem search -rd fluent-plugin' to find plugins"
efk_fluentd_1 exited with code 1
root@sys:/efk# vi fluentd/conf/fluent.conf
root@sys:/efk# docker-compose up fluentd
efk_elasticsearch_1 is up-to-date
Starting efk_fluentd_1 ... done
Attaching to efk_fluentd_1
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '4.2.0'
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: gem 'fluent-plugin-fortigate-log-parser' version '0.2.1'
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: gem 'fluent-plugin-fortigate-syslog-parser' version '0.1.1'
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: gem 'fluentd' version '1.11.3'
fluentd_1        | 2020-10-08 03:54:13 +0000 [info]: 'flush_interval' is configured at out side of <buffer>. 'flush_mode' is set to 'interval' to keep existing behaviour
fluentd_1        | 2020-10-08 03:54:14 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Unknown parser plugin 'fortigate_syslog_parser'. Run 'gem search -rd fluent-plugin' to find plugins"
efk_fluentd_1 exited with code 1

**Comment by cosmo0920** [comment]
Your pasted docker-compose file is invalid.
Please paste valid docker-compose file.

**Comment by cosmo0920** [comment]
Ah, I got it.

fluent-plugin-fortigate-syslog-parser does not contain parser plugin.
https://github.com/yteraoka/fluent-plugin-fortigate-log-parser/blob/master/lib/fluent/plugin/out_fortigate_log_parser.rb#L2
If you want to use this plugin's parser part, please send a request to extract parser plugin on parsing part.
