### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by leefbiant** [fluent/fluentd-docker-image#213]
I developed a plug-in parser_test.rb, placed in the /home/docker/fluentd/plugin directory, docker started mapping the directory
run as -v /home/docker/fluentd/plugin:/fluentd/plugin
But there is an error when starting, config error file = "/fluentd/etc/fluent.conf" error_class = Fluent :: ConfigError error = "Unknown parser plugin 'test'

**Comment by kenhys** [comment]
If FLUENT_PLUGIN environment variable is not set, the default search path of plugin is /etc/fluent/plugin.
