### ISSUE TITLE
Can't install plugin that need native extension with Alpine based image

### ISSUE THREAD

**Issue by EricFortin** [fluent/fluentd-docker-image#22]
I am trying to install fluent-plugin-flume in 0.12.21 alpine based image and receive this error:

```
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h
```
Digging in the dockerfile, I can see that after installing fluentd the necessary package to build native extension is removed:

```
apk del build-base ruby-dev
```

Is this a bug or is the intended use is to re-install those in my docker file and remove them after my plugin is installed like so (note it does require switching to root user momentarily though) ?

```
USER root
RUN apk --no-cache --update add \
                            build-base \
                            ruby-dev && \
    gem install fluent-plugin-flume && \
    apk del build-base ruby-dev && \
    rm -rf /tmp/* /var/tmp/* /var/cache/apk/*
USER fluent
```

I guess I can see why you remove those 2 packages as they are quite large but wanted to confirm.

Thanks

**Comment by repeatedly** [comment]
> Is this a bug or is the intended 

This is intended. We want to keep docker image small.

**Comment by EricFortin** [comment]
Thanks !
