### ISSUE TITLE
FluentD issue with fluentd-plugin-kafka. SSL not working

### ISSUE THREAD

**Issue by uttamanand** [fluent/fluentd-docker-image#226]
FluentD is not shutting down itself when it is trying to connect to kafka securely over ssl.

FluentD version -: 1.9.1
fluentd-plugin-kafka version -: 0.11.1

The configuration of fluentd and compose file is attached for your reference. 

I don't see any error in the log file of the fluentd service too. Attached the log file. I see fluentd worker Running in logs but the container gets killed. In the docker ps command, it shows "unhealthy container".

Could you please check. 

[log.txt](https://github.com/fluent/fluentd-docker-image/files/4934784/log.txt)

[docker-compose.txt](https://github.com/fluent/fluentd-docker-image/files/4934770/docker-compose.txt)
[fluentd-conf.txt](https://github.com/fluent/fluentd-docker-image/files/4934771/fluentd-conf.txt)

**Comment by uttamanand** [comment]
The fluentd container is receiving the Graceful stop and then its stopping and I dont see any error in the log message. Please help. 


Logs of fluentD with fluent-plugin-kafka installed -:
-----------
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:09:34 +0000 [warn]: parameter 'ssl_client_cert_key_password' in <source>
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   @type kafka_group
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   @label @kafka-dev
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   ssl_ca_cert /etc/ssl/certs/ca_cert.pem
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   ssl_client_cert "/etc/ssl/certs/client_cert.pem"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   ssl_client_cert_key "/etc/ssl/certs/client_cert_key.pem"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   ssl_client_cert_key_password sfdsf
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   brokers "kafdv1:9092"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   consumer_group "fluentdDev"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   topics "devTest"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   format "text"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   add_prefix "kafka-dev"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    |   start_from_beginning false
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | </source> is not used.
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:09:34 +0000 [info]: #0 starting fluentd worker pid=20 ppid=6 worker=0
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:09:34 +0000 [info]: #0 listening port port=24224 bind="0.0.0.0"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:09:34 +0000 [info]: #0 fluentd worker is now running worker=0
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:05 +0000 [info]: Received graceful stop
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:06 +0000 [info]: #0 fluentd worker is now stopping worker=0
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:06 +0000 [info]: #0 shutting down fluentd worker worker=0
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:06 +0000 [info]: #0 shutting down input plugin type=:kafka_group plugin_id="object:2ae111270098"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:06 +0000 [info]: #0 shutting down input plugin type=:forward plugin_id="object:2ae111340888"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:07 +0000 [info]: #0 shutting down output plugin type=:elasticsearch_dynamic plugin_id="object:2ae11122de50"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:07 +0000 [info]: #0 shutting down filter plugin type=:record_transformer plugin_id="object:2ae111266700"
logging_fluentd_dev.1.70nbdumua21r@mwrk05    | 2020-07-17 15:11:08 +0000 [info]: Worker 0 finished with status 0

**Comment by huangweikuna** [comment]
@uttamanand Is it solved？ I also encountered the same problem

**Comment by kenhys** [comment]
maybe development package is not pre-installed and kafka is not built against it.
I guess that it is custom image issue, so I'll close it.
