### ISSUE TITLE
Alpine images still using: FROM alpine:3.9, any plans to go to 3.11.5+? It has a fix for fluent-plugin-google-cloud.

### ISSUE THREAD

**Issue by MrVentzi** [fluent/fluentd-docker-image#228]
Are there any plans on upgrading to later apline version?

We want to use fluent-plugin-google-cloud but it only works with the debian images and they have critical and high vunlerabilities as per this issue: https://github.com/fluent/fluentd-docker-image/issues/224 

Thanks

**Comment by repeatedly** [comment]
Patch: https://github.com/fluent/fluentd-docker-image/pull/229

**Comment by kenhys** [comment]
Fixed via #229
