### ISSUE TITLE
Confused over multiarch and image sizes

### ISSUE THREAD

**Issue by jnewbigin** [fluent/fluentd-docker-image#230]
Hi,
I am trying to build a project based on fluentd for both x86_64 and aarch64/arm64.

I have been using these 2 images:
fluent/fluentd:v1.11.2-debian-1.0
fluent/fluentd:v1.11.2-debian-arm64-1.0

But these images are hugely different in size:
fluent/fluentd:v1.11.2-debian-1.0 == 79.09 MB
fluent/fluentd:v1.11.2-debian-arm64-1.0 == 331.97 MB

So I did some more digging and I found the _official_ images such as
fluentd:v1.9.1-debian-1.0

It seems that v1.9.1 is the latest version under the _official_ repo - so I looked deeper into version 1.9.1
Those images appear to be multiarch but docker hub says:
linux/amd64 == 78.53 MB
linux/arm64/v8 == 75.96 MB

So I am confused about:
What are the official images, and should I find the latest version there
Why are the images different sizes between the libraries.

And ultimately, how can I get an arm image which is ~80MB in size

If anyone can help me out it would be greatly appreciated.

**Comment by grantbeattie** [comment]
Could be an oversight; the arm64 build uses `ruby:2.6-buster` as its base, while the amd64 build uses `ruby:2.6-slim-buster`.

https://github.com/fluent/fluentd-docker-image/blob/master/Dockerfile.template.erb#L39

The resulting image built using `ruby:2.6-slim-buster` on arm64 is roughly the same size as amd64 (~200MB).

**Comment by jnewbigin** [comment]
That fix seems to work for me. I opened a PR
