### ISSUE TITLE
fluentd docker image v1.11.5 keeps detaching/recovering forwarder server and keep logging unknow key errors

### ISSUE THREAD

**Issue by mkanna** [fluent/fluentd-docker-image#240]
I am using Fluentd latest docker image and customized by installing only two plugins for elastic search & sumologic.
able to ship JAVA logs to another fluentd collector server which is again pushing to ELK. Everything works fine. but the log keeps writing these entries. I have nowhere defined any KEY values. There is no issues with the forward server and all entries were showing up in ELK. but not sure why these entries keep logging. Is this a Bug? what needs to be done here? Please help !

2020-12-17 09:51:27 +0000 [warn]: #0 detached forwarding server '' host="XYZ.COM" port=24224 hard_timeout=true
2020-12-17 09:51:27 +0000 [warn]: #0 recovered forwarding server '' host="XYZ.COM" port=24224
Unknown key: MAX-AGE = 604800
Unknown key: MAX-AGE = 604800
Unknown key: SameSite = None
Unknown key: MAX-AGE = 604800
Unknown key: MAX-AGE = 604800
Unknown key: SameSite = None
Unknown key: MAX-AGE = 604800
Unknown key: MAX-AGE = 604800
Unknown key: SameSite = None
2020-12-17 09:54:07 +0000 [warn]: #0 detached forwarding server '' host="XYZ.COM" port=24224 phi=45.03231031743231 phi_threshold=16
2020-12-17 09:54:27 +0000 [warn]: #0 recovered forwarding server '' host="XYZ.COM" port=24224
Unknown key: MAX-AGE = 604800
Unknown key: MAX-AGE = 604800
Unknown key: SameSite = None
Unknown key: MAX-AGE = 604800
Unknown key: MAX-AGE = 604800
Unknown key: SameSite = None

To Reproduce
[fluentd_files.txt](https://github.com/fluent/fluentd-docker-image/files/5709204/fluentd_files.txt)
docker run -itd -v <local_log_path>:/fluentd/log/ --name="dev" dev-fluentd:latest

**Comment by mkanna** [comment]
hi, can someone please comment.

**Comment by paprickar** [comment]
Hey @mkanna,

sadly can`t help but I have the same problem with https://github.com/SumoLogic/fluentd-output-sumologic

**Comment by alexnguyen91** [comment]
I think using `disable_cookies` should help, I have the same problem and after set `disable_cookies` those messages disappear

**Comment by andrewphilp-ut** [comment]
Thanks @alexnguyen91, setting `disable_cookies` to true resolved the log spam for me.

**Comment by kenhys** [comment]
About disable_cookies, see https://github.com/SumoLogic/fluentd-output-sumologic/blob/main/README.md#configuration
