### ISSUE TITLE
Use a static UID and GID

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluentd-docker-image#245]
The general consensus of Docker best practices include running as a non-root user and using a high static UID and GID ([hexops/dockerfile](https://github.com/hexops/dockerfile) for reference). It would be great if the _Fluentd_ docker image is updated to provide a static UID and GID; this shouldn't have any impact on existing use but should make using the image in systems such as _Kubernetes_ easier and more deterministic.

This is related to issue https://github.com/fluent/fluentd-docker-image/issues/48 but I think it deserves it's own issue to track the work.

**Comment by stevehipwell** [comment]
I think this is also related to https://github.com/fluent/fluentd-docker-image/issues/173, @repeatedly @edsiper would you be interested in a PR to set fixed UID and GID values?

**Comment by repeatedly** [comment]
We moved account setup to runtime by https://github.com/fluent/fluentd-docker-image/pull/78 before.
This trick is now not needed, right?

**Comment by stevehipwell** [comment]
@repeatedly the changes in that PR around UID and GID (actually GID wasn't set) appear to have been undone. I assume because the change of UID in entrypoint would need root access.

My preference would be to set an absolute UID and GID in the dockerfile. This would work well with K8s and doesn't need any extra permissions at runtime.

**Comment by stevehipwell** [comment]
@repeatedly @edsiper the current behaviour on Alpine doesn't look correct, as the user's group doesn't seem to be set to `fluent`. I suspect that `-g` might have been used where `-G` should have been used?

https://github.com/fluent/fluentd-docker-image/blob/06b03600fe2978fa708a3f60a1868e2200b9572f/Dockerfile.template.erb#L167

This results in the following output.

```shell
PS ~> docker run --rm -it --entrypoint /bin/sh fluent/fluentd:v1.14
$ id
uid=100(fluent) gid=65533(nogroup) groups=65533(nogroup)
```

If changes are needed here it'd be great if at same time the user uid (e.g. `adduser -S -G fluent -u 1000 fluent`) and group gid (e.g. `addgroup -S -g 1000 fluent`) could be set to absolute values?

**Comment by stevehipwell** [comment]
@kenhys are you in a position to comment on https://github.com/fluent/fluentd-docker-image/issues/245#issuecomment-958818730?

**Comment by kenhys** [comment]
> the current behaviour on Alpine doesn't look correct, as the user's group doesn't seem to be set to fluent. I suspect that -g might have been used where -G should have been used?

```
% docker run -u root --rm -it fluent/fluentd:v1.14-1  /bin/sh
/ # id fluent
uid=100(fluent) gid=65533(nogroup) groups=65533(nogroup),65533(nogroup)
/ # adduser -S -g fluent foo
/ # id foo
uid=101(foo) gid=65533(nogroup) groups=65533(nogroup),65533(nogroup)
/ # adduser -S -G fluent bar
/ # id bar
uid=102(bar) gid=101(fluent) groups=101(fluent),101(fluent)
```

Surely, `-G` should be used in this case.

**Comment by stevehipwell** [comment]
Thanks @kenhys.
