### ISSUE TITLE
Windows container not compatible with AKS

### ISSUE THREAD

**Issue by josephbmanley** [fluent/fluentd-docker-image#246]
Just giving a heads up that the Windows container cannot run on Azure (AKS or Container Instances) due to using too new of a version of Windows.

VM Image Reference:
```
Publisher: microsoft-aks  
Offer: aks-windows  
SKU: aks-2019-datacenter-core-smalldisk-2012  
Version: 17763.1579.201208  
```

This was response from running the `fluent/fluentd:v1.11-windows-1` image with AKS on Azure:
```
[rpc error: code = Unknown desc = a Windows version 10.0.18362-based image is incompatible with a 10.0.17763 host, rpc error: code = Unknown desc = Error response from daemon: Get https://REDACTED.azurecr.io/v2/fluentd/manifests/latest: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]
```

**Comment by repeatedly** [comment]
Does anyone know how to avoid this problem?
I'm not a Windows expert but OS version `10.0.18362` is not newer version.
From https://hub.docker.com/_/microsoft-windows-servercore, `10.0.18362` is used since `05/21/2019` so AKS should support it with option or something.

**Comment by josephbmanley** [comment]
@repeatedly
I presumed it was since `10.0.17763` is the current AKS VM version. I would definitely agree, it should deploy a newer version.

For some of our containers, we had to use the base windows image: https://hub.docker.com/_/microsoft-windows

**Comment by cosmo0920** [comment]
> code = Unknown desc = a Windows version 10.0.18362-based image is incompatible with a 10.0.17763 host, rpc error: code = Unknown desc = Error response from daemon:

This is because Windows containers cannot run under older Windows 10 revisions.
The above log complains that Windows 10 10.0.18362(Windows 10 1903)-based image is not compatible older Windows 10 10.0.17763 (Windows 10 1809) environment.

**Comment by josephbmanley** [comment]
Yes, this that's the managed AKS instance configuration.
