### ISSUE TITLE
rewrite_tag_filter plugin not found

### ISSUE THREAD

**Issue by DavidHe1127** [fluent/fluentd-docker-image#247]
Try to run fluentd container with a sample config file but receive error below when starting up the container:

```
2021-01-22 21:20:28 +0000 [error]: config error file="/fluentd/etc/fluentd.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
```

---
## Environment

fluent/fluentd:v1.6-debian-1

## Config

```yml
<source>
  @type http
  port 8080
  bind 0.0.0.0
</source>

<filter *.*>
  @type record_transformer
  enable_ruby
  <record>
    something ${record["message"]["foo"]}
    remove_keys ${record["message"]["baz"]}
  </record>
</filter>

<match *.*>
  @type rewrite_tag_filter
  <rule>
    key message
    pattern /^\[(\w+)\]/
    tag $1.${tag}
  </rule>
</match>
```

Any idea?

**Comment by cosmo0920** [comment]
This is because fluent-plugin-rewrite-tag-filter is not contained this image.

If you want to build your own image, please refer to the section: https://github.com/fluent/fluentd-docker-image#how-to-build-your-own-image

**Comment by daveseff** [comment]
And when following the instructions to build a custom image doesn't work, then what? 

I created a custom image, And I see:
```
# gem list

...
fluent-config-regexp-type (1.0.0)
fluent-plugin-rewrite-tag-filter (2.4.0)   <---- There's my plugin
fluentd (1.16.2)
...
```

I get:
```
config error file="/fluentd/etc/fluent.conf" error_class=Fluent::NotFoundPluginError error="Unknown filter plugin 'rewrite_tag_filter'. Run 'gem search -rd fluent-plugin' to find plugins"
```

**Comment by CarlosFdez77** [comment]
Same problem

**Comment by kenhys** [comment]
> I created a custom image, And I see:

Usually  Dockerfile was properly customized, rewrite_tag_filter will be recognized.
There is some hints in startup log message.

**Comment by kenhys** [comment]
It was already answered by https://github.com/fluent/fluentd-docker-image/issues/247#issuecomment-797300547, so I'll close this issue.
