### ISSUE TITLE
Cannot get example to work.

### ISSUE THREAD

**Issue by bpsizemore** [fluent/fluentd-docker-image#25]
I'm trying to run the example that is included in the README and I'm getting and issue with file is not writeable. I've included the output when running the command as well as the logs from the container after it fails.

```
root@Bubu:~/fluent# docker run -d -p 24224:24224 -v /data:/fluentd/log fluent/fluentd
8913bd8e5221293b8011c02d7825d5b5dd47ba6420355cf959ba15fa4ff88a5a
root@Bubu:~/fluent# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
root@Bubu:~/fluent# docker logs 8913
2016-04-27 20:01:51 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-04-27 20:01:51 +0000 [info]: starting fluentd-0.12.21
2016-04-27 20:01:51 +0000 [info]: gem 'fluentd' version '0.12.21'
2016-04-27 20:01:51 +0000 [info]: adding match in @mainstream pattern="docker.**" type="file"
2016-04-27 20:01:51 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error="out_file: `/fluentd/log/docker.20160427_0.log` is not writable"
2016-04-27 20:01:51 +0000 [info]: process finished code=256
2016-04-27 20:01:51 +0000 [warn]: process died within 1 second. exit.
```

**Comment by tagomoris** [comment]
Check owner&permission of `/data` and uid&gid of docker container. These should be configured properly.

**Comment by repeatedly** [comment]
No response. If you still have a problem with proper permission, please reopen it.

**Comment by katopz** [comment]
Hm, I did have exactly problem via Docker for Windows, It appear
```
$ ll ~/fluentd
total 0
drwxr-xr-x 1 u6034838 1049089 0 Jul 12 18:40 log/
```
Is this permission enough? btw it at `~/fluentd/log/` but judge from error it try to access `/fluentd/log/` ?

**Comment by repeatedly** [comment]
I'm not familiar with Windows environment so I can't judge this is the bug of our Docker image or additional step is needed on Windows environment.
We need help from windows users.

**Comment by katopz** [comment]
Yeah, I think so.
```
$ docker run --log-driver=fluentd --log-opt fluentd-address=127.0.0.1:24224 fluent/fluentd echo "Hello Fluentd"
```
It's working fine on my Mac after set `/data` location.
No worry about Windows env, I just testing around while boring at work.
