### ISSUE TITLE
Default locations are not same as bin and documentation 

### ISSUE THREAD

**Issue by uCatu** [fluent/fluentd-docker-image#255]
See docs:
https://docs.fluentd.org/v/0.12/deployment/plugin-management#add-a-plugin-via-etc-fluent-plugin
Referring to `/etc/fluent/plugin`

While in code we are using `-p /fluentd/plugins`
https://github.com/fluent/fluentd-docker-image/blob/c848dfe1b8616cd7e59a7c01d83817dad8865766/entrypoint.sh.erb#L20

Same goes to `conf` file, when trying to use default binary:
```Traceback (most recent call last):
	9: from /usr/bin/fluentd:23:in `<main>'
	8: from /usr/bin/fluentd:23:in `load'
	7: from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/bin/fluentd:8:in `<top (required)>'
	6: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	5: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
	4: from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/command/fluentd.rb:344:in `<top (required)>'
	3: from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/supervisor.rb:727:in `configure'
	2: from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `build'
	1: from /usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `open'
/usr/lib/ruby/gems/2.7.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /etc/fluent/fluent.conf (Errno::ENOENT)```

**Comment by kenhys** [comment]
https://docs.fluentd.org/v/0.12/deployment/plugin-management#add-a-plugin-via-etc-fluent-plugin
is referred for general purpose, in the other hand, the docker image does not follow it. It seems it is an intentional change (I guess)
beause of docker image is a one of distribution of fluentd.
So, it may be better to mention it in https://github.com/fluent/fluentd-docker-image/blob/master/README.md.

**Comment by kenhys** [comment]
Already it was answered https://github.com/fluent/fluentd-docker-image/issues/255#issuecomment-816540985, so  I'll close this issue.
