### ISSUE TITLE
Multi-arch image for v1.13.x 

### ISSUE THREAD

**Issue by sid226** [fluent/fluentd-docker-image#285]
Hi,
I can see multiarch  image   v1.9.1 here (https://hub.docker.com/_/fluentd) but not the latest version of fluentd (v1.13.x)

I have tried  building  following dockerfiles for s390x architecture, Working as expected. 
* [v1.13/alpine/Dockerfile](https://github.com/fluent/fluentd-docker-image/blob/master/v1.13/alpine/Dockerfile)
* [v1.13/debian/Dockerfile](https://github.com/fluent/fluentd-docker-image/blob/master/v1.13/debian/Dockerfile)

any possibility of releasing latest multiarch  image (v1.13.x) ? 

Thanks!

**Comment by cosmo0920** [comment]
These images are handled in official repository: https://github.com/docker-library/official-images/pull/10854

We'd already registered Fluentd v1.14 images there. We shouldn't provide older images....

**Comment by cosmo0920** [comment]
@kenhys How do we treat this issue? I think that it's too late to handle this issue here.

**Comment by kenhys** [comment]
@cosmo0920 
I agree that it's too late.
