### ISSUE TITLE
Docker build stucks Windows Image - LTSC2019 and 2004

### ISSUE THREAD

**Issue by marciogmorales** [fluent/fluentd-docker-image#295]
Hello,
I usually built this image without any problem on ltsc2019 and 2004 (SAC) images, however myself and collegues are getting stuck here:

```
19 gems installed
Successfully installed win32-service-1.0.1
1 gem installed
Successfully installed win32-ipc-0.7.0
1 gem installed
Successfully installed win32-event-0.6.3
1 gem installed
Successfully installed windows-pr-1.2.6
1 gem installed
*** Removed specs cache ***
```

I noticed an issue opened one year ago number [208](https://github.com/fluent/fluentd-docker-image/issues/208) reported the same behavior. Don't know if any Windows Update might causing this as well as any ruby bug. I already tried the latest ruby version, no success. Also, something caught my attention is that the CPU utilization for the dockerd process remains around 30%~50% until manually close the process.

Docker engine version: 20.10.5
Host Windows Version: 10.0.17763  Build 17763
Base image: mcr.microsoft.com/windows/servercore:ltsc2019  (latest)

Any clue?

**Comment by kenhys** [comment]
I'll check again.

**Comment by kenhys** [comment]
Hmm,

I've tried, but it succeeds.

```
Successfully installed windows-pr-1.2.6
1 gem installed
*** Removed specs cache ***
Removing intermediate container bc12d96d4e4f
 ---> c7fe6539c065
Step 7/11 : RUN powershell -Command "Remove-Item -Force C:\ruby26\lib\ruby\gems\2.6.0\cache\*.gem; Remove-Item -Recurse -Force 'C:\ProgramData\chocolatey'"
 ---> Running in 1dc732a3222b
Removing intermediate container 1dc732a3222b
 ---> 51b3d476033c
Step 8/11 : COPY fluent.conf /fluent/conf/fluent.conf
 ---> b7edc6c2cc9d
Step 9/11 : ENV FLUENTD_CONF="fluent.conf"
 ---> Running in 5b93d8d6bf2a
Removing intermediate container 5b93d8d6bf2a
 ---> bb3555f30ec2
Step 10/11 : EXPOSE 24224 5140
 ---> Running in 5a85aca0a178
Removing intermediate container 5a85aca0a178
 ---> 4c7bec41b766
Step 11/11 : ENTRYPOINT ["cmd", "/k", "fluentd", "--config", "C:\\fluent\\conf\\fluent.conf"]
 ---> Running in a1f751c33302
Removing intermediate container a1f751c33302
 ---> 120320d82638
[Warning] One or more build-args [VERSION] were not consumed
Successfully built 120320d82638
Successfully tagged fluent/fluentd:v1.14.1-windows-ltsc2019-1.0
```

Here is the software vesions.


Git revision:

```
$ git log --oneline -n 1
55c68e8 (HEAD -> master, upstream/master, origin/master, origin/HEAD) Add Fluentd v1.14.1 images

```

Windows version:

```
>ver

Microsoft Windows [Version 10.0.19043.1237]
```

Based image:

```
> docker pull mcr.microsoft.com/windows/servercore:ltsc2019
ltsc2019: Pulling from windows/servercore
Digest: sha256:2b33eda096538c803fbf0c03dc7ea42c3c1b713e30aae03116d989867eda2bf8
Status: Image is up to date for mcr.microsoft.com/windows/servercore:ltsc2019
mcr.microsoft.com/windows/servercore:ltsc2019
```

Docker version:

```
> docker --version
Docker version 20.10.8, build 3967b7d
```

Build with:

```
make DOCKERFILE=v1.14/windows-ltsc2019 VERSION=v1.14.1-windows-ltsc2019-1.0
```

Ruby:

```
 ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x64-mingw32]
```

**Comment by kenhys** [comment]
If newer msys2 was available, it may be resolved, but not released yet. :thinking:

**Comment by marciogmorales** [comment]
Hello,
Thanks for the test, but sounds like you built using Windows 10 20H1, right?

Did you try with a server version? I do believe the issue is related to the Server version. I tried both LTSC and 2004.

**Comment by kenhys** [comment]
> Thanks for the test, but sounds like you built using Windows 10 20H1, right?

Yes, not the server edition.

**Comment by marciogmorales** [comment]
Bring this up.. Anyone else faced the same issue on a Windows Server version?

**Comment by repeatedly** [comment]
You need to put `fluent.conf` in building directory.
https://github.com/fluent/fluentd-docker-image/tree/master/v1.14/windows-ltsc2019 includes it.

**Comment by kenhys** [comment]
This issue is not reproducible anymore.
I'll close it.
