### ISSUE TITLE
Issue: Fluentd on alpine: On upgrade of ruby to version 3.0.3, ext_monitor gem is no longer supported

### ISSUE THREAD

**Issue by vrangana** [fluent/fluentd-docker-image#302]
Evironment: Fluentd on alpine

Issue: On upgrade of busybox (to 1.34.1-r3) and which resulted in ruby upgrade to version 3.0.3.157. So after the upgrade system unable to install "ext_monitor" gem, is this gem vital for fluentd operation. If yes, is there any alternative gem which can be used instead of "ext_monitor". Please provide me with necessary clues. Any assistance is appreciated.

Error: #6 129.7 ERROR:  Error installing ext_monitor:
#6 129.7        ext_monitor-0.1.2 requires Ruby version ~> 2.3. The current ruby version is 3.0.3.157.

**Comment by kenhys** [comment]
If you use Ruby 3, `ext_monitor` is not required.

**Comment by vrangana** [comment]
@kenhys Thanks for the confirmation
