### ISSUE TITLE
Upgrade Ruby to 2.7 or 3.1

### ISSUE THREAD

**Issue by ashie** [fluent/fluentd-docker-image#304]
Currently our Docker images uses Ruby 2.6:
https://github.com/fluent/fluentd-docker-image/blob/341fa8130b3f8685f7a9a5abe58a08f77731e47d/Dockerfile.template.erb#L45

EOL date of Ruby 2.6 is 2022-03-31:https://www.ruby-lang.org/en/downloads/branches/
We need to upgrade Ruby by the date.

Because Ruby 3.0 has some known problems (that are solved in 3.1), I want to skip it.

**Comment by fujimotos** [comment]
* 2.6 is EOL soon (March).
* We need to update the Ruby version.

**Comment by ashie** [comment]
We have still several known issues with Ruby 3.1 on Windows: https://github.com/fluent/fluentd/pull/3585
So I'll choose 2.7 for a while.

**Comment by kenhys** [comment]
And more, buster reaches EOL at 2022-08, ruby:2.7-slim-bullseye is recommended.

**Comment by kenhys** [comment]
Working on windows side.
https://github.com/fluent/fluentd-docker-image/pull/309
https://github.com/fluent/fluentd-docker-image/pull/310

**Comment by kenhys** [comment]
https://github.com/fluent/fluentd-docker-image/pull/311

**Comment by kenhys** [comment]
It will be shipped when v1.14.5 was ready.

**Comment by ashie** [comment]
Done
