### ISSUE TITLE
Add Alpine ARM64 image

### ISSUE THREAD

**Issue by stevehipwell** [fluent/fluentd-docker-image#314]
There currently isn't an Alpine ARM64 image available for Fluentd; with Alpine being the default image OS I'd have expected it to be the first OS with ARM64 support. This is related to https://github.com/fluent/fluentd-docker-image/issues/313, which could facilitate this.

**Comment by LorisFriedel** [comment]
Same situation here, would be nice to have an Alpine ARM64 version of fluentd image!

**Comment by kenhys** [comment]
Thank you for raising attention.

Alpine image is still provided by historically reason, but not recommended to use.
(The point of performance or interoperability)

There is no intention extending support for alpine and as we have debian-based arm64 image,  it is recommended to use it.

It result in widely requests for alpine arm64, we might reconsider, but not for now.
