### ISSUE TITLE
Images for "1.14.6" release still not available on Docker Hub 8 days after version release

### ISSUE THREAD

**Issue by astencel-sumo** [fluent/fluentd-docker-image#322]
Hi,

Fluentd v1.14.6 has been released on March 31st https://github.com/fluent/fluentd/releases/v1.14.6.

Is there a reason why the images for version v1.14.6 are still not available on Docker Hub?

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/70892616/162384248-65a85bd0-a35e-4c3d-ab4a-407705831ec9.png">

**Comment by cosmo0920** [comment]
Ping @ashie or @kenhys?

**Comment by astencel-sumo** [comment]
Oh, I can see there's a pull request prepared https://github.com/fluent/fluentd-docker-image/pull/321. I wonder why it's not merged yet. 🙂

**Comment by ashie** [comment]
Hmm, build failed.
Alpine 3.9 is choosed, why?
https://hub.docker.com/repository/registry-1.docker.io/fluent/fluentd/builds/ac539e79-0550-46f6-a151-9add1e52a436

**Comment by ashie** [comment]
Hmm, succeeded to build on my local environment...

**Comment by ashie** [comment]
> Hmm, build failed. Alpine 3.9 is choosed, why? https://hub.docker.com/repository/registry-1.docker.io/fluent/fluentd/builds/ac539e79-0550-46f6-a151-9add1e52a436

My mistake. I triggered 1.4, not 1.14.

**Comment by ashie** [comment]
Done.
