### ISSUE TITLE
Fluentd for redhat ubi

### ISSUE THREAD

**Issue by vrangana** [fluent/fluentd-docker-image#328]
Hi Team,

Good Day team. Is it possible to use fluentd docker image over Rehat UBI 8 for k8s container deployment? Please confirm back with your inputs and it would be helpful if you could share the relevant resources / references. Thanks in advance.

Have a good day.

**Comment by edsiper** [comment]
We don't have a Uni image for Fluentd. But Calyptia provides a certified
one for Fluent Bit:

https://catalog.redhat.com/software/container-stacks/detail/61d87331e4578f8bf95ed96f
