### ISSUE TITLE
Create custom Fluent Docker Image 0.12.24 -> 0.12.26

### ISSUE THREAD

**Issue by mpas** [fluent/fluentd-docker-image#33]
When creating your own docker image for Fluentd and would like to use the 0.12.26 then some config on the custom image should be changed. Otherwise you will get the notification that plugins cannot be found.

I needed to add these 2 lines to my build of an image based on v0.12.26 of the DockerHub image.

ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
ENV GEM_PATH /home/fluent/.gem/ruby/2.3.0:$GEM_PATH

**Comment by repeatedly** [comment]
I build v0.12.26-2 tag for fluentd v0.12.26 and alpine linux 3.4.
Check it!

**Comment by mpas** [comment]
Yep works, i do not even have to pass the lines:

ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
ENV GEM_PATH /home/fluent/.gem/ruby/2.3.0:$GEM_PATH

Thanks for releasing the new image
