### ISSUE TITLE
Dockerhub image isn't updated for 3 weeks

### ISSUE THREAD

**Issue by SehiiRohoza** [fluent/fluentd-docker-image#360]
Hello,

Accordingly to GitHub https://github.com/fluent/fluentd/tree/master and https://github.com/fluent/fluentd-docker-image/tree/master/v1.16 Fluentd v.16.2 was released 3 weeks ago and Docker images were updated 2 weeks ago. Meanwhile, DOCKER OFFICIAL IMAGE https://hub.docker.com/_/fluentd wasn't updated and "doesn't have any tags that have "1.16.2" in their names".

To make it more confusing, you can find the latest version here https://hub.docker.com/r/fluent/fluentd, and link to this page at https://github.com/fluent/fluentd-docker-image, meanwhile it's described as SPONSORED OSS.

Please solve it or at least update descriptions if some repo is deprecated.

**Comment by ashie** [comment]
We need send a pull request to https://github.com/docker-library/official-images.
e.g.)
https://github.com/docker-library/official-images/issues?q=label%3Alibrary%2Ffluentd

I'll do it.

**Comment by ashie** [comment]
Done: https://github.com/docker-library/official-images/pull/15468
