### ISSUE TITLE
Cannot use on-build image

### ISSUE THREAD

**Issue by F21** [fluent/fluentd-docker-image#41]
I am trying to use the on-build image to build a customized image of fluentd.

My Dockerfile is copied verbatim from the README:

```Dockerfile
FROM fluent/fluentd:latest-onbuild
MAINTAINER your_name <...>
USER fluent
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
RUN gem install fluent-plugin-secure-forward
EXPOSE 24284
CMD fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

When I run `docker build . `, I get:
```
Sending build context to Docker daemon 57.34 kB
Step 1 : FROM fluent/fluentd:latest-onbuild
# Executing 2 build triggers...
Step 1 : COPY fluent.conf /fluentd/etc/
lstat fluent.conf: no such file or directory
```

Docker is 1.11.2 running on Ubuntu 16.04 64-bit.

**Comment by repeatedly** [comment]
Does fluent.conf exist in `.` ?

**Comment by F21** [comment]
No, I did not add my own `fluent.conf`, because the readme says that `fluent.conf` is automatically included in the build process.

**Comment by repeatedly** [comment]
> Write your Dockerfile and configuration files, and/or your own plugin files if needed.
> Files below are automatically included in build process:

This means docker build includes these files in build process without manual copies.
This is why we provide on-build image.

**Comment by F21** [comment]
Ah, I see! That makes sense.
