### ISSUE TITLE
Building from custom Dockerfile fails with docker-compose

### ISSUE THREAD

**Issue by pydolan** [fluent/fluentd-docker-image#47]
When trying to use a custom Dockerfile with docker-compose, I get the following error:

```
Building fluentd
Step 1 : FROM fluent/fluentd:latest-onbuild
# Executing 2 build triggers...
Step 1 : COPY fluent.conf /fluentd/etc/
ERROR: Service 'fluentd' failed to build: lstat fluent.conf: no such file or directory
```

I'm using the sample Dockerfile in repo:

```Dockerfile
FROM fluent/fluentd:latest-onbuild
MAINTAINER YOUR_NAME <...@...>
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH

USER root
RUN apk --no-cache --update add sudo build-base ruby-dev && \

    sudo -u fluent gem install fluent-plugin-secure-forward && \

    rm -rf /home/fluent/.gem/ruby/2.3.0/cache/*.gem && sudo -u fluent gem sources -c && \
    apk del sudo build-base ruby-dev && rm -rf /var/cache/apk/*

EXPOSE 24284

USER fluent
CMD exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT
```

My docker-compose.yml entry for fluentd:

```yaml
fluentd:
    build: ./docker/fluentd
    restart: always
```

**Comment by repeatedly** [comment]
> ERROR: Service 'fluentd' failed to build: lstat fluent.conf: no such file or directory

I'm not familiar with docker-compose but this said the cause. You need to prepare your fluentd configuraiton.

See this instruction: https://github.com/fluent/fluentd-docker-image#how-to-build-your-own-image

**Comment by pydolan** [comment]
I thought I had everything configured properly, but it turns out my conf file was named *fluentd.conf* instead of *fluent.conf*.  After updating the file name, fluentd builds okay using Docker Compose.
