### ISSUE TITLE
td-agent availability

### ISSUE THREAD

**Issue by vyscond** [fluent/fluentd-docker-image#54]
Hi guys, i'm starting my journey at fluentd this weekend. Do you guys can tell me with the td-agent is already part of this image? If not how could i install it properly?

**Comment by repeatedly** [comment]
Sorry, I can't understand your question.

> the td-agent is already part of this image?

What doesn this sentence mean?
Do you want td-agent, not fluentd, or others?

**Comment by repeatedly** [comment]
I assume your refer http://docs.fluentd.org/articles/high-availability article, but I'm not sure you want. configurarion?

**Comment by edsiper** [comment]
@vyscond if you refer to if 'td-agent version' is used in this Docker image, the answer is _no_. This image uses the Fluentd gem:

https://github.com/fluent/fluentd-docker-image/blob/master/Dockerfile#L17
