### ISSUE TITLE
don't use user ubuntu inside docker image

### ISSUE THREAD

**Issue by mcbain** [fluent/fluentd-docker-image#6]
Don't create an extra user 'ubuntu' but use root for running. 
The users ubuntu (uid) has no permissions to access data mounted in volumes.

**Comment by repeatedly** [comment]
Thanks for pointing this out.

Could you show me the example file for updating our Dockerfile?

**Comment by mcbain** [comment]
Simply use the user 'root' which already exists and can access also files in mounted volumes

**Comment by tagomoris** [comment]
Docker document says: https://docs.docker.com/articles/security/
```
Docker containers are, by default, quite secure; especially if you take care of running your processes inside the containers as non-privileged users (i.e., non-root).
```

IMO, community container image should be built as secure as possible.
@mcbain you can create your own Fluentd image to execute fluentd process as root privilege at your own risk.

**Comment by mcbain** [comment]
@tagomoris The problem of creating a users inside of containers is that they use their own permissions to access files mounted in host-volumes. 
This prevents the usage of your docker image to collect log files from the host.

http://cloud-mechanic.blogspot.de/2014/10/storage-concepts-in-docker-persistent.html
