### ISSUE TITLE
Latest Image fails when extended

### ISSUE THREAD

**Issue by jaygorrell** [fluent/fluentd-docker-image#62]
Very simple repro:

Using:
```
FROM fluent/fluentd:latest
USER root
RUN apk --no-cache --update add sudo
```
Results:
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
Bus error
```

Replacing the base image with alpine:3.4 (same as fluent/fluentd:latest) fixes the problem -- you can even see it fetch the same file without an issue.

I did just rebuild from master here and it worked fine so perhaps it's the image pushed to Docker hub that just needs a cache refresh.

**Comment by repeatedly** [comment]
So the problem is dockerhub, not Dockerfile itself, right?

**Comment by jaygorrell** [comment]
The problem is with the image on docker hub, yes, but I wouldn't say it's a docker hub problem. 

I have no idea what your delivery process is, but my best guess is that there was a problem with a cached layer in the image -- try rebuilding without cache and pushing to the hub. That should do it from what I could tell by testing the Dockerfile out.

**Comment by repeatedly** [comment]
Hmm... we use dockerhub's automatic build feature, so
we don't push built image to dockerhub manually.

BTW, we will re-run build image.

**Comment by jaygorrell** [comment]
Very odd. I'd be happy to try again after a rebuild.

**Comment by repeatedly** [comment]
Now building... > https://hub.docker.com/r/fluent/fluentd/builds/

**Comment by jaygorrell** [comment]
Got it - pulled and saw the new layers come down. Unfortunately, same result though. Are you able to reproduce?

It seems very strange that building locally produced an image that worked but these from the Docker hub aren't... when they should be the same. For what it's worth the `v0.14-latest` tag works just fine.

**Comment by repeatedly** [comment]
Today, we updated Dockerfile for jemalloc but it should not affect Dockerhub build...
I will try to reproduce this issue later.

**Comment by ericsage** [comment]
I had this same issue today trying to extend the image with some plugins. Using fluent-gem by itself also caused a segmentation fault. There's definitely something wrong with the current image.

**Comment by ericsage** [comment]
Also it would be nice if you could just include the name of some plugins as an environment variable, like ```docker run -e "FLUENTD_PLUGINS=fluent-plugin-elasticsearch" fluent/fluentd```
so that we wouldn't have to derive and maintain a second downstream image just for plugins.

**Comment by repeatedly** [comment]
I didn't find the cause of this problem but I commented out `LD_PRELOAD` line from Dockerfile.
Does anyone check latest image?

**Comment by repeatedly** [comment]
> docker run -e "FLUENTD_PLUGINS=fluent-plugin-elasticsearch" fluent/fluentd

This approach can't specify plugin version and install options, so this is incomplete way.
If we can resolve these problem, we should provide FLUENTD_PLUGINS like feature.

**Comment by ericsage** [comment]
I just pulled the latest image and api and fluent-gem are both working again, thanks!

**Comment by repeatedly** [comment]
Thanks for the check!
I'm not sure why using jemalloc causes this problem with dockerhub.
jaygorrell says local build has no problem.
jemalloc is good for avoiding memory fragmentation issue, so
we will try to avoid this bus error later.

**Comment by jaygorrell** [comment]
I didn't test but if @ericsage verified then we should be good to close this. Thanks for the attention on it. :)
