### ISSUE TITLE
Docker Tags

### ISSUE THREAD

**Issue by jonapich** [fluent/fluentd-docker-image#64]
Hi,

Is it possible to obtain the "latest" image from docker hub using a tag other than "latest"? Otherwise said, I'd like to pin my version on the current one and not get the next update automatically. Is there a missing tag?

**Comment by repeatedly** [comment]
https://hub.docker.com/r/fluent/fluentd/tags/

We provide lots of tag. Is it enough?

**Comment by jonapich** [comment]
Is there a way I can download "latest" without using "latest"? It's the only one that was pushed "5 days ago".

Is it because it is not an official release, and thus doesn't have an official docker-version to go with?

Comparatively, please take a look at the elasticsearch tags. The "latest" tag is also the "5" tag.

**Comment by repeatedly** [comment]
So you want v0.12-latest tag?

**Comment by jonapich** [comment]
There seems to be quite a bit of confusion, I'll try to explain in more details.

Use case: In a production environment, it is a bad practice to use "latest" as the version. You don't download packages (apt, chef, puppet, pip...) without actually specifying the version; doing so is a recipe for disaster. By always pinning to a static version # that is not going to change ever, you can control and test updates in a dev/staging environment before upgrading your production environment.

The "latest" is 5 days old but the most recent version tag (v0.14.8) is 1 month old. The Readme doesn't mention anything about versions; timestamps is the best guess we can take. Does "latest" actually point to the v,0,14,8 build, and I was just thrown off by the timestamps difference? Or is "latest "a new version by itself that has no version number?

If you believe the "latest" version is production ready, then there should be a static tag to go with it too (such as v0.14.8, v0.14.6, etc). But then I had a doubt that maybe you're just tagging it with a version after you proved its worth in production; so I asked the second question: "Is it because it is not an official release, and thus doesn't have an official docker-version to go with?".

To me, the correct flow would be to upload the new image and then tag it with a static version tag such as v0.14.8 and the likes. Then you move the latest tag to point to the latest image. In the end, there should always be 2 tags pointing to your latest version: the version tag and the latest tag.

Here are a few more examples:

https://hub.docker.com/r/library/rabbitmq/tags/
https://hub.docker.com/r/library/nginx/tags/
https://hub.docker.com/r/library/redis/tags/

Thanks!

**Comment by repeatedly** [comment]
> Use case: In a production environment, it is a bad practice to use "latest" as the version.

Yeah. We recommend to not use latest on production.

> you believe the "latest" version is production ready

Correct. This is why latest refers v0.12 versions.
v0.14 is not production ready.

> To me, the correct flow would be to upload the new image and then tag it with a static version tag such as v0.14.8 and the likes

We did it. We create new version tag when fluentd released and updated our Dockerfile.

**Comment by jonapich** [comment]
Okay great, thanks for the precision. Since the timestamps don't match, it would be great having this information on top of the readme file. This way I could find out when v0.14 is stable :)

**Comment by repeatedly** [comment]
Okay. I will update README soon.

**Comment by repeatedly** [comment]
Added: https://github.com/fluent/fluentd-docker-image#docker-image-tag-and-fluentd-versions
