### ISSUE TITLE
empty plugins directory breaks image builds

### ISSUE THREAD

**Issue by camallen** [fluent/fluentd-docker-image#7]
When creating my own image using `FROM fluent/fluentd:latest` the ONBUILD COPY cmd stops exectution at the copy command and breaks subsequent builds. Adding ant file to the directory forces correct behaviour.

```
$ docker build --force-rm --no-cache .
Sending build context to Docker daemon 86.53 kB
Step 0 : FROM fluent/fluentd:latest
# Executing 2 build triggers
Trigger 0, COPY fluent.conf /fluentd/etc/
Step 0 : COPY fluent.conf /fluentd/etc/
Trigger 1, COPY plugins/* /fluentd/plugins/
Step 0 : COPY plugins/* /fluentd/plugins/
Removing intermediate container 34e3b50362bf
No source files were specified
````
http://docs.docker.com/engine/reference/builder/#copy
perhaps  `ONBUILD COPY plugins/* /fluentd/plugins/` could become `ONBUILD COPY plugins/ /fluentd/plugins/` ??

**Comment by repeatedly** [comment]
I see.

From `If <src> is a directory, the entire contents of the directory are copied, including filesystem metadata.`, `ONBUILD COPY plugins /fluentd/plugins/` is better?

**Comment by camallen** [comment]
yeah basically specify the directory instead of the wildcard match. I haven't tested, I ended up using your upstream docker file with an empty placeholder file in ./plugins/

**Comment by repeatedly** [comment]
I pushed changes. After several times, DockerHub provides fixed version.
