### ISSUE TITLE
Feature request: Provide image based on something other than Alpine due to DNS issues

### ISSUE THREAD

**Issue by ryanwalls** [fluent/fluentd-docker-image#72]
Alpine seems to not play well with Kubernetes.  See https://github.com/gliderlabs/docker-alpine/blob/master/docs/caveats.md#dns and https://github.com/SumoLogic/fluentd-kubernetes-sumologic/issues/8.

There have even been images built to get around this DNS issue like: https://github.com/janeczku/docker-alpine-kubernetes.  

So it would be nice to create a tag with each release based on a different image than Alpine.  E.g.  One of these: https://hub.docker.com/_/buildpack-deps/

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd-docker-image/pull/71 is enough?

**Comment by ryanwalls** [comment]
@repeatedly Yep, that would be great.

**Comment by repeatedly** [comment]
This is handled by #71 and #49
