### ISSUE TITLE
Status of using jemalloc?

### ISSUE THREAD

**Issue by Lawouach** [fluent/fluentd-docker-image#74]
Hi,

I've been seeing the fluentd forwarder agent consuming quite a lot of memory and as I run it in a Kubernetes environment, it's gets OOM killed and restarted (which is a good Kubernetes thing to do). Still, it looks like if we were using jemalloc, memory wouldn't be fragmented as much.

However, I see that it was reverted in 94691d0872667d5cea1f051faa5f0e8e7cead40 and I don't quite understand the reason why.

What's the status of using jemalloc with this image today?

Thanks,

**Comment by repeatedly** [comment]
>  I don't quite understand the reason why.

This breaks docker image build.

@edsiper How about the progress?

**Comment by Lawouach** [comment]
With an Alpine backend or Debian based image?

**Comment by repeatedly** [comment]
Both

**Comment by Lawouach** [comment]
I see. That's unfortunate because fluentd is quite memory hungry :/

**Comment by repeatedly** [comment]
Why? You don't want to use jemalloc?

**Comment by Lawouach** [comment]
I would like to actually. As per https://github.com/kubernetes/kubernetes/issues/32762, as I understand it, only when jemalloc does fluentd keeps its memory usage straight. 

Since your image doesn't ship it anymore, I'm saying it's unfortunate.

**Comment by repeatedly** [comment]
No no no. I don't say "We don't use jemalloc".
The problem is previous commit breaks docker image build.
This is why I reverted the commit.

If the problem is fixed, we use jemalloc.

**Comment by Lawouach** [comment]
I see. As long as your image can eventually ship with jemalloc, I'm a happy man :)

**Comment by Lawouach** [comment]
I am waiting for the new Debian based image to be merged and released. Then I'll use it and see if I can also use jemalloc on it.

**Comment by edsiper** [comment]
Jemalloc support will be there shortly (patch was reverted because a technical issue in Docker Hub)

**Comment by Lawouach** [comment]
Hey there,

That's good news. If shortly means, in a matter of a few days, then I'll be happy to wait to try it and the new Debian image for sure!

Thanks,

**Comment by edsiper** [comment]
shortly = ASAP! :)

I've pushed a jemalloc branch (to be reviewed) that adds Jemalloc to Debian based images. Images based on Alpine cannot work with Jemalloc due to an issue with Musl. 

Please try any 0.12 or 0.14 Debian image and send us some feedback:

https://github.com/fluent/fluentd-docker-image/tree/jemalloc

**Comment by Lawouach** [comment]
Thanks. The branch looks good to me so far. I'll try it asap.

**Comment by repeatedly** [comment]
Debian image now uses jemalloc.
