### ISSUE TITLE
Network access problem from image

### ISSUE THREAD

**Issue by wimnat** [fluent/fluentd-docker-image#76]
I created an image using the example Dockerfile but added in an extra plugin - fluent-plugin-splunk.

This plugin errors out when running the container with a "Connection reset by peer".

As a troubleshooting step, I logged in to the container and i was able to ping my host.  I then installed telnet and tried to telnet to my Splunk port - this failed.

I then started a standard centos container for testing and i was able to successfully telnet to my Splunk server port.

I then changed my Dockerfile to use the Debian fluent image and faced the same problem.

It seems strange that from other containers i can reach my Splunk server but from the fluentd images i am unable to connect (even though ping works).

**Comment by kenhys** [comment]
I guess Fluentd v0.12 or v0.14 era, so I'll close it.
