### ISSUE TITLE
Dockerfile should chown directories as root

### ISSUE THREAD

**Issue by atombender** [fluent/fluentd-docker-image#77]
The way this Dockerfile is written makes it impossible, in practice, to use with Kubernetes, which mounts all volumes as `root`.

Since you specify `USER` to drop privileges, and then mkdir/chown the log directory inside the Dockerfile, it's too late to do anything with the volume by the time the container is run.

The fix — and this applies to any Docker image — is to start as root and to drop privileges in a script invoked by `ENTRYPOINT`.

[Here](https://github.com/docker-library/postgres/blob/5159417968c6a08e2ed784498cba28f22a74b03e/9.6/Dockerfile#L61) is an example from the official PostgreSQL image (entrypoint script is [here](https://github.com/docker-library/postgres/blob/5159417968c6a08e2ed784498cba28f22a74b03e/9.6/docker-entrypoint.sh)). That script uses gosu to drop privileges, but I prefer [su-exec](https://github.com/ncopa/su-exec/) myself.

Another reason why dropping privileges with `USER` is a bad idea is that it makes it impossible to exec into the container as root, which in turn makes it impossible to do certain things (gdb, strace) inside the container.

**Comment by repeatedly** [comment]
One developer tries to resolve this problem and write good patch before: https://github.com/fluent/fluentd-docker-image/pull/60
How about this approach?

**Comment by atombender** [comment]
That's exactly how I would do it. I didn't consider the possibility of allowing overriding the user UID, but that looks like an interesting option.

**Comment by repeatedly** [comment]
Do you have any concern above patch?
I'm not expert docker ecosystem so I want more experts check above patch.
No breaking compatibiliy or something.

**Comment by ValFadeev** [comment]
I have just submitted a patch completing the previous word and potentially addressing most of the concerns

**Comment by repeatedly** [comment]
Closed via #78
