### ISSUE TITLE
Minimise image footprint

### ISSUE THREAD

**Issue by Brandl** [fluent/fluentd-docker-image#8]
I'm currently trying to setup containerized log aggregation on my coreos-cluster, unfortunately the docker pull of this container takes way longer than expected and most other services waiting for it to come online just time out.

I don't have any ideas how to resolve this in a clean fashion other than using a stripped down fluentd-image.

There are multiple ways to achieve this, the easiest and also most efficient would be not to use a full fledged ubuntu as base, but rather Alpine Linux:
https://github.com/gliderlabs/docker-alpine

I think most people expect this container to be lightweight and fast, just like fluent.

**Comment by tagomoris** [comment]
Your point is reasonable for me too. I'm thinking about to use thinner OS as a base as you meant, but I have no time to do that right now.
Pull requests for that are welcome :)
