### ISSUE TITLE
How to Run this fluentd docker image as non-root user

### ISSUE THREAD

**Issue by alamzeeshan** [fluent/fluentd-docker-image#81]
I am using the Apline version https://github.com/fluent/fluentd-docker-image#apline-version 

When I run this, it is running as ROOT

After running this as docker image

    docker exec -it b3c565091160 /bin/sh
    
    cat /etc/passwd

    fluent:x:1000:1000::/home/fluent:

And

    /home/fluent # ps -ef
    PID   USER     TIME   COMMAND
        1 root       0:00 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
        8 root       0:12 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins
       22 root       0:00 /bin/sh
       28 root       0:00 ps -ef
    /home/fluent # whoami
    root

How can run this Fluentd as fluent user, specifically user 1000 instead of ROOT?

**Comment by repeatedly** [comment]
Could you try new images?

**Comment by repeatedly** [comment]
No response
