### ISSUE TITLE
Fluent is no longer a default recognised user

### ISSUE THREAD

**Issue by AnkurJain10** [fluent/fluentd-docker-image#84]
Hi, My code was working fine till 12th May 2017 but from 15th May 2017, I started getting this error:

Step 5/8 : RUN gem install fluent-plugin-elasticsearch
 ---> Running in 5fa0ac7253e1
ERROR: Service 'fluentd' failed to build: linux spec user: unable to find user fluent: no matching entries in passwd file

My fluentd docker file is: 

FROM fluent/fluentd:latest-onbuild
USER fluent
WORKDIR /home/fluent
ENV PATH /home/fluent/.gem/ruby/2.3.0/bin:$PATH
RUN gem install fluent-plugin-elasticsearch
RUN gem install fluent-plugin-secure-forward
EXPOSE 24224
CMD fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT

Any reason why it can no longer identify fluent as a valid user and what can be done to fix this?

**Comment by repeatedly** [comment]
See:

https://groups.google.com/forum/#!topic/fluentd/yP8JQ1ZxKs8
https://github.com/fluent/fluentd-docker-image#3-customize-dockerfile-to-install-plugins-optional

**Comment by AnkurJain10** [comment]
The method specified in there for Apline version (Latest and v0.14.16/v0.12.35 or later)  makes it such that there is no fluent user and everything is done as root, which is not a good thing to do in a docker container. Is there a way to make the default user as fluent in this version?

**Comment by repeatedly** [comment]
Hmm... previous image also executes almost commands in root user context.
The main differece between newer and older is moving fluent user and permission handling to entrypoint.sh to resolve fixed id issue.
This approach is same as postgresql image. So the docker official postgresql is also not good?
