### ISSUE TITLE
syslog input to retain source hostname

### ISSUE THREAD

**Issue by port22** [fluent/fluentd-docker-image#89]
I am running fluentd as a docker container listening for 514/udp to aggregate syslog messages sent by bare metal machines, forwarding all to graylog2 via gelf/udp.

Now in Graylog2 all messages have the generated docker hostname of the fluentd container in the source field.
How can I retain the original hostname from which the syslog message has been sent?

```
<source>
 @type syslog
 port 514
 tag syslog
</source>

<match **>
    @type gelf
    host 192.168.1.15
    port 12201
    protocol udp
    flush_interval 2
</match>

```
much appreciated

**Comment by repeatedly** [comment]
See: http://docs.fluentd.org/v0.12/articles/in_syslog#sourcehostnamekey

**Comment by port22** [comment]
I tried adding  source_hostname_key, but still I get the fluentd container hostname in the source field:

```
<source>
 @type syslog
 port 514
 tag syslog
 source_hostname_key
</source>
```

**Comment by repeatedly** [comment]
> source_hostname_key

Why empty? Need key name. See document again.

**Comment by repeatedly** [comment]
And maybe, `use_record_host` parameter is needed: https://github.com/emsearcy/fluent-plugin-gelf/blob/master/lib/fluent/plugin/out_gelf.rb#L7

**Comment by port22** [comment]
thanks for your answers .. 
I read the docs more than twice on this part, but I don't get it gramatically:
```
 If set the value
```
which value? 
I understand that I have to set a static value like "webserver01" ...
But I have tons of servers sending their logs to fluent on port 514. 

I tried to set both options to "true":
```
<source>
 @type syslog
 port 1514
 tag syslog
 source_hostname_key true
 use_record_host true
</source>

```
But still nothing changes. "source" is always the  hostname of the fluentd docker container

**Comment by repeatedly** [comment]
The entire explanation is "The field name of the client’s hostname. If set the value, the client’s hostname will be set to its key. The default is nil (no adding hostname)."

the value -> The field name of the client’s hostname -> source_hostname_key

> use_record_host true

This is gelf plugin, not syslog plugin. See my comment again: https://github.com/fluent/fluentd-docker-image/issues/89#issuecomment-315950398

How about `source_hostname_key host` and `use_record_host true`?
