### ISSUE TITLE
v0.12-onbuild appears to install fluentd 0.14.20 

### ISSUE THREAD

**Issue by spohn-acc** [fluent/fluentd-docker-image#94]
Hello,  I have been trying to build a new image using the v0.12-onbuild tag (I also tried the v0.12.39-onbuild and 0.12.38 and few further back) but once I ran the image I see in the log this message:

2017-08-01 23:31:57 +0000 [info]: starting fluentd-0.14.20 pid=10

Using this in Dockerfile
```
FROM fluent/fluentd:v0.12-onbuild

RUN apk add --update --virtual .build-deps \
        sudo build-base ruby-dev \
 && sudo gem install \
        fluent-plugin-elasticsearch \
        fluent-plugin-multi-format-parser \
        fluent-plugin-ecs-metadata-filter \
        fluent-plugin-record-modifier \
 && sudo gem sources --clear-all \
 && apk del .build-deps \
 && rm -rf /var/cache/apk/* \
           /home/fluent/.gem/ruby/2.3.0/cache/*.gem
```

What could be going on?  Is it correct that I have fluentd v0.14 running?

**Comment by spohn-acc** [comment]
Found my problem, this plugin `fluent-plugin-ecs-metadata-filter` is the one pushing the version up.  When I removed it, I was back on v0.12

2017-08-02 00:00:20 +0000 [info]: starting fluentd-0.12.39

**Comment by repeatedly** [comment]
JFYI: https://docs.fluentd.org/v0.12/articles/plugin-management#plugin-version-management

**Comment by spohn-acc** [comment]
Yes, thank you!  For anyone else out there, this did the trick for that plugin `fluent-plugin-ecs-metadata-filter:0.1.1`
