### ISSUE TITLE
ppc64le docker image

### ISSUE THREAD

**Issue by vaibhavsood** [fluent/fluentd-docker-image#98]
Hi, I'm looking to enable docker containers for packages like fluentd for multiple architectures on dockerhub, starting off with a focus on ppc64le. Wanted to check on the work that will be involved to do that

I have locally been able to successfully test ppc64le changes to the dockerfiles in this repo - changes for enabling additional arch would be minimum.

Would like to know how a multi-arch image for this can be initiated? The official images have this method for enabling multi-arch : https://github.com/docker-library/official-images#multiple-architectures, however this repo isnt an official image yet. Would the first step be to make this an official image or are there any other ways the dockerhub fluentd image can be enabled for ppc64le?

**Comment by repeatedly** [comment]
> Would the first step be to make this an official image or are there any other ways the dockerhub fluentd image can be enabled for ppc64le?

I'm not sure how to do it. If someone points the docs for ppc64le in 3rd party repository, we can follow it.

**Comment by vaibhavsood** [comment]
We need to follow the official-image multi-arch process as per here: https://github.com/docker-library/official-images#multiple-architectures

Steps involved 

1) As per the link above, the upstream repo (in this case the current repo) should have a single Dockerfile for all arches. Hence the first step will be to get ppc64le changes into the dockerfiles in this repo

2) Next, since this is not an official repo, it needs to be proposed as an official repo as per here: https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository
    They support 3rd party repos as well

3) The manifest files under docker-library/official-images will have the appropriate arch tags, docker handles building once the image is official (eg. file https://github.com/docker-library/official-images/blob/master/library/erlang)

Please let me know any questions/comments, thanks!

**Comment by vaibhavsood** [comment]
Hi @repeatedly, want to check back on the earlier conversation

I'm at IBM and can help with getting a public CI nightly build setup for fluentd on ppc64le

Want to check if that will be useful? (and maybe it can also help the docker official image part of this)

**Comment by repeatedly** [comment]
@vaibhavsood Sorry, we were working on releasing stable v0.14. We can now work on it.

For becoming official repo, we need to update our dockerfile for it and you have a patch, right?

> Want to check if that will be useful?

Yeah, it is useful :)

**Comment by repeatedly** [comment]
BTW, do you also need ppc64le support for fluent-bit docker image?

**Comment by vaibhavsood** [comment]
Hi @repeatedly , thanks for the response!

The first step to making this an official repo will be to raise a PR on the official-images repo, some similar PRs are here: https://github.com/docker-library/official-images/pulls

Once this PR goes through, the docker image would become official and will come up under https://hub.docker.com/explore/

Then the next step would be to make this image multi-arch, get the ppc64le (and other changes?) into the dockerfiles here and subsequently again work with Docker (and DockerHub) to extend the official image created in the first step to publish a multi-arch official image

I would like to go ahead and create the PR from step 1 in the official-images repo. This will atleast get the process kickstarted and will help to get any comments/opinon from the docker guys. (please feel free to also modify/comment etc on this PR as my aim initially is just to start the process)

As for fluent-bit i'm not sure, i guess ill start for fluentd and can then take it up in the next stage

**Comment by vaibhavsood** [comment]
Hi @repeatedly, 

Based on the earlier comments on this thread, I had raised a PR https://github.com/docker-library/official-images/pull/3724 to request creation of a official docker image for fluentd.

@tianon has responded to the PR with some review comments on the dockerfile for fluentd: https://github.com/docker-library/official-images/pull/3724#issuecomment-355423609

It would be great if you could comment on them as it will help to take this process forward

Thanks a lot!!

**Comment by ghatwala** [comment]
@repeatedly - Having already added ppc64le(power) support to existing travis builds in this repo via this merged PR -https://github.com/fluent/fluentd-docker-image/pull/123 .Can we now look to make this into a official multi-arch docker image via the steps given above by @vaibhavsood  .

**Comment by ghatwala** [comment]
@repeatedly - any comments on above ?

**Comment by vaibhavsood** [comment]
Hi @repeatedly , another gentle reminder for my earlier comment, need your help with comments posted by @tianon for the dockerfile https://github.com/docker-library/official-images/pull/3724#issuecomment-355423609

**Comment by lag-linaro** [comment]
@repeatedly what's stopping you from submitting pull-requests to this project?

**Comment by repeatedly** [comment]
> what's stopping you from submitting pull-requests to this project?

I'm not sure... if someone sends PR, we can merge the patch.
To be honest, I don't have enough time to handle this theme so I want more active maintaier for this project.

**Comment by vaibhavsood** [comment]
@lag-linaro , yes that should be possible. i think the first step will be to address these comments from tianon: https://github.com/docker-library/official-images/pull/3724#issuecomment-355423609

**Comment by lag-linaro** [comment]
Okay, I'm happy to help here.

@repeatedly, there is a slight issue though.  I submitted a PR about 2 weeks ago to test the waters a little, but as yet haven't had any response.  I am a little reluctant to put lots of effort into making this project a) multi-arch and b) part of Docker's Official Images ecosystem if submissions aren't going to be reviewed/accepted.

@repeatedly if I put the work in, will you support me in reviewing/accepting the work?

**Comment by seelam** [comment]
Can you please push these power images to docker hub?

**Comment by repeatedly** [comment]
fluentd is now docker official image.

https://hub.docker.com/_/fluentd
