### ISSUE TITLE
dockerhub documentation out of date

### ISSUE THREAD

**Issue by briceburg** [fluent/fluentd-docker-image#99]
The documentation for the fluentd/fluentd image on dockerhub ( https://hub.docker.com/r/fluent/fluentd/ ) appears out of date. IMO This repo's README provides improved and current documentation, and it would be a good thing to replace the existing dockerhub w/ the README contents.

The version info in header is important -- as is dumping usage of `:latest`.

**Comment by repeatedly** [comment]
Thanks for pointing this out.
I just copied current README to docker hub.

**Comment by briceburg** [comment]
@repeatedly LGTM! Thank you. Much improved. 

I was playing w/ the onbuild image earlier and thought some optimizations could be made -- will open a separate issue for discussion.
